### ISSUE TITLE
Problem with unknown type name ‘VIXDISKLIB_OPEN_FLAGS’

### ISSUE THREAD

**Issue by gabrielsusin** [xuru/vixDiskLib#2]
I'm trying to setup the vixDiskLib by running the follow command line:

`$ sudo python setup.py install`

 but this error keeps appearing:

`In file included from /usr/include/python2.7/numpy/ndarraytypes.h:1761:0,`
                ` from /usr/include/python2.7/numpy/ndarrayobject.h:17,`
             `    from /usr/include/python2.7/numpy/arrayobject.h:4,`
             `    from vixDiskLib/vixDiskBase.c:457:`
 ` vixDiskLib/vixDiskBase.c:1413:71: error: unknown type name ‘VIXDISKLIB_OPEN_FLAGS’
 static CYTHON_INLINE PyObject* __Pyx_PyInt_From_VIXDISKLIB_OPEN_FLAGS(VIXDISKLIB_OPEN_FLAGS value); ` 
` ...` 
` ...` 
` ...` 
` error: command 'x86_64-linux-gnu-gcc' failed with exit status 1` 

it also says i'm using a deprecated NumPy API

 `warning: #warning "Using deprecated NumPy API, disable it by " "#defining   NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp] 
  #warning "Using deprecated NumPy API, disable it by " \ `

but i've installed the latest version using apt-get. Installing using pip-install also didn't work.

I'm using Ubuntu 14.04 and Python 2.7.6

**Comment by xuru** [comment]
Honestly I'm surprised this is still working at all. It's been at least 5 years since I've had access to VMware, so I haven't been updating it. You are welcome to submit a pull request and I'll merge it, but I have no way of testing, or running this anymore.
